version: '3'

services:
  fincatica-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: fincaticabackend:1.0.0
    container_name: fincatica-backend
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}